# Configurações principais do HypedDungeon
settings:
  debug: false
  default-language: "pt_BR"

# Configurações das dungeons
dungeon:
  # Número máximo de jogadores por dungeon
  max-players: 4
  # Número mínimo de jogadores para iniciar
  min-players: 1
  # Tempo de espera entre dungeons em segundos (1 hora)
  cooldown: 3600

# Configurações de dados
data:
  save-player-data: true
